events { }

http {
    upstream backend {
        server express-api:3001;
        server express-api:3001 backup;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend;
        }
    }
}
